// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpggczwvftfswkrdpghn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZ2djend2ZnRmc3drcmRwZ2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTA2MzgsImV4cCI6MjA2ODU4NjYzOH0.ogkirxgjgZb6SLZ4CZxK5gZq63m6r08kmiNQbvLMw7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});